resources:
  - ../../
patches:
  - target:
      kind: Deployment
      name: architecture-control-plane-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {"name": "REMOTE_WORKSPACE_DEFAULT_EXECUTOR", "value": "github_actions"}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {"name": "REMOTE_WORKSPACE_PERSISTENT_ENABLED", "value": "false"}
