apiVersion: v1
kind: Service
metadata:
  name: {{ include "acp.fullname" . }}
spec:
  selector: { app: {{ include "acp.name" . }}, component: api }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
