from __future__ import annotations

import os
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC_RULES = ROOT / 'deploy' / 'prometheus' / 'alerts' / 'acp-alerts.src.yml'
RUNBOOK_MAP = ROOT / 'deploy' / 'prometheus' / 'alerts' / 'runbook-map.yml'
GENERATED_RULES = ROOT / 'deploy' / 'prometheus' / 'alerts' / 'acp-alerts.yml'
RUNBOOK_INDEX = ROOT / 'docs' / 'runbooks' / 'INDEX.md'
DEFAULT_RUNBOOK_BASE_URL = 'http://localhost:8000/runbooks'


def _load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text())


def main() -> None:
    rules_doc = _load_yaml(SRC_RULES)
    runbook_map = _load_yaml(RUNBOOK_MAP)
    base_url = os.getenv('RUNBOOK_BASE_URL', DEFAULT_RUNBOOK_BASE_URL).rstrip('/')

    alerts_by_name: dict[str, str] = runbook_map['alerts']
    runbooks: dict[str, dict[str, str]] = runbook_map['runbooks']

    for group in rules_doc.get('groups', []):
        for rule in group.get('rules', []):
            alert_name = rule.get('alert')
            if not alert_name:
                continue
            slug = alerts_by_name.get(alert_name)
            if not slug:
                raise SystemExit(f'missing runbook slug for alert {alert_name}')
            if slug not in runbooks:
                raise SystemExit(f'missing runbook definition for slug {slug}')
            annotations = rule.setdefault('annotations', {})
            annotations['runbook_url'] = f'{base_url}/{slug}'
            annotations['runbook_slug'] = slug

    GENERATED_RULES.write_text(yaml.safe_dump(rules_doc, sort_keys=False))

    lines = [
        '# Alert Runbooks',
        '',
        'This index is generated by `scripts/render_alert_rules.py`.',
        '',
        '| Alert | Runbook | Local URL |',
        '| --- | --- | --- |',
    ]
    for alert_name, slug in sorted(alerts_by_name.items()):
        meta = runbooks[slug]
        local_url = f'{base_url}/{slug}'
        lines.append(
            f"| `{alert_name}` | [{meta['title']}](./{slug}.md) | `{local_url}` |"
        )
    RUNBOOK_INDEX.write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
