from __future__ import annotations

import subprocess  # noqa: F401

from app.ops.postgres_backup_restore_support import (
    BACKUP_FILE_MAGIC as BACKUP_FILE_MAGIC,
    DEFAULT_COMMAND_TIMEOUT_SECONDS as DEFAULT_COMMAND_TIMEOUT_SECONDS,
    DEFAULT_ENCRYPTION_CHUNK_SIZE as DEFAULT_ENCRYPTION_CHUNK_SIZE,
    DEFAULT_ENCRYPTION_KDF_ITERATIONS as DEFAULT_ENCRYPTION_KDF_ITERATIONS,
    DEFAULT_VERIFY_TABLES as DEFAULT_VERIFY_TABLES,
    BackupArtifact as BackupArtifact,
    BackupIntegrityError as BackupIntegrityError,
    BackupMetadataError as BackupMetadataError,
    BackupObjectStoreError as BackupObjectStoreError,
    CommandSpec as CommandSpec,
    ObjectStoreConfig as ObjectStoreConfig,
    RetentionResult as RetentionResult,
    _database_slug as _database_slug,
    _ensure_output_dir as _ensure_output_dir,
    _now_utc as _now_utc,
    _resolve_backup_source as _resolve_backup_source,
    _safe_label_component as _safe_label_component,
    _sha256_file as _sha256_file,
    _timestamp_token as _timestamp_token,
    _tool_database_url as _tool_database_url,
    _tool_env as _tool_env,
    admin_database_url as admin_database_url,
    backup_database as backup_database,
    build_backup_command as build_backup_command,
    build_parser as build_parser,
    build_restore_command as build_restore_command,
    decrypt_backup_file as decrypt_backup_file,
    delete_file_from_object_store as delete_file_from_object_store,
    download_file_from_object_store as download_file_from_object_store,
    encrypt_backup_file as encrypt_backup_file,
    format_s3_uri as format_s3_uri,
    get_object_store_client as get_object_store_client,
    infer_metadata_reference_from_backup_reference as infer_metadata_reference_from_backup_reference,
    is_s3_uri as is_s3_uri,
    load_backup_metadata as load_backup_metadata,
    main as main,
    parse_s3_uri as parse_s3_uri,
    plan_backup_set_upload as plan_backup_set_upload,
    prune_backup_artifacts as prune_backup_artifacts,
    recreate_database as recreate_database,
    resolve_object_store_config as resolve_object_store_config,
    restore_database as restore_database,
    rotate_backup_encryption_passphrase as rotate_backup_encryption_passphrase,
    run_backup_restore_drill as run_backup_restore_drill,
    run_command_from_file as run_command_from_file,
    run_command_to_file as run_command_to_file,
    sanitize_database_url as sanitize_database_url,
    upload_backup_set as upload_backup_set,
    upload_file_to_object_store as upload_file_to_object_store,
    verify_backup_artifact_integrity as verify_backup_artifact_integrity,
    verify_restored_database as verify_restored_database,
)

if __name__ == "__main__":
    raise SystemExit(main())