apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: acp-api
  labels:
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
