apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: architecture-control-plane
commonLabels:
  app.kubernetes.io/name: architecture-control-plane
  app.kubernetes.io/part-of: architecture-control-plane
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - api-service.yaml
  - api-deployment.yaml
  - worker-jobs-service.yaml
  - worker-jobs-deployment.yaml
  - worker-outbox-service.yaml
  - worker-outbox-deployment.yaml
  - api-pdb.yaml
  - api-hpa.yaml
